#!/usr/local/bin/python
#
#  Copyright 2017, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

# This file define constants used in the MODIS Level 2 Downloader Message Queue (MQ) modules

# Integer constants:

CONST_FAILURE_STATUS = 0; 
CONST_SUCCESS_STATUS = 1;
CONST_FILE_NOT_FOUND = 2;

# String constants:

# CONST_CLUSTER_JOB_STRING = '__clusterjob';  # This is the convention used by Ancillary Filling to create temporary directory.  We look for this string.

#  Constants for

CONST_GETFILE_URI = "https://oceandata.sci.gsfc.nasa.gov/cgi/getfile";
CONST_SEARCH_URI  = "https://oceandata.sci.gsfc.nasa.gov/search/file_search.cgi";

# Constant to control the looping in get_file_checksum.py script to control how many attempts and how long to sleep in between attempts.

CONST_GET_FILE_CHECKSUM_MAX_ATTEMPTS = 50
CONST_GET_FILE_CHECKSUM_MAX_SLEEP_IN_BETWEEN_WAITS = 5

# Constant to control the looping in perform_download_only.py script to control how many attempts in download and how long to sleep in between attempts.

CONST_PERFORM_DOWNLOAD_ONLY_MAX_ATTEMPTS = 50
CONST_PERFORM_DOWNLOAD_ONLY_MAX_SLEEP_IN_BETWEEN_WAITS = 5

# Constant to control the looping in create_generic_download_list.py script to control how many attempts in file search and how long to sleep in between attempts.

# CONST_LIST_CREATOR_MAX_ATTEMPTS = 50;
# CONST_LIST_CREATOR_MAX_SLEEP_IN_BETWEEN_WAITS = 5;

# Constants to control how long should a job be monitored.

CONST_MAX_WAIT_DURATION_BETWEEN_CHECKS = 4
CONST_MAX_AGE_BEFORE_CONSIDERED_STALE = 300   # If a file is more than 5 minutes old, we consider the downloader job to be stale.

# To test
#
#CONST_MAX_AGE_BEFORE_CONSIDERED_STALE = 0
#CONST_MAX_WAIT_DURATION_BETWEEN_CHECKS = 1;

# A list of supported parameters in the file search.

# CONST_SUPPORTED_SENSORS_LIST = ["viirs","aqua","terra","aquarius"]
# CONST_SUPPORTED_LEVELS_LIST  = ["L2","L3","L3m","L3b","L4"]
