#  Copyright 2017, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

import os
import time

def get_local_pdt_time():

    # Get the current time in PDT.
    os.environ["TZ"]="US/Pacific"
    time.tzset();
    o_localtime = time.localtime(time.time())

    return(o_localtime);

def get_local_gmt_time():

    # Get the current time in GMT.
    os.environ["TZ"]="UTC"
    time.tzset();
    o_localtime = time.localtime(time.time())

    return(o_localtime);


if __name__ == "__main__":

    print("get_local_pdt_time()",get_local_pdt_time());
    print("get_local_gmt_time()",get_local_gmt_time());
