#  Copyright 2017, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM
#
# This function is a wrapper to the raise_sigevent() function.
# It will fetch the URL where the sigevent manager is running.

import os;
import requests;
import subprocess;

from raise_sigevent import raise_sigevent;

def raise_sigevent_wrapper(sigevent_type,
                           sigevent_category,
                           sigevent_description,
                           sigevent_data,
                           sigevent_debug_flag):

    debug_module = 'raise_sigevent_wrapper:';
    debug_mode   = 0;

    if ((os.getenv('CRAWLER_SEARCH_DEBUG_FLAG') == 'true') or (sigevent_debug_flag)):
        debug_mode   = 1;

    sigevent_url = os.getenv('GHRSST_SIGEVENT_URL','');
    sigevent_provider = 'JPL';

    sigevent_source   = 'GENERIC_MODULE';
    if (os.getenv('MYENV','') != ''): sigevent_source = os.getenv('MYENV','');

    # Raise a sigevent that should work.

    raise_sigevent(sigevent_url,
                   sigevent_provider,
                   sigevent_source,
                   sigevent_type,
                   sigevent_category,
                   sigevent_description,
                   sigevent_data);

if __name__ == '__main__':
    debug_module = 'raise_sigevent_wrapper:';
    debug_mode   = 0;

    if (os.getenv('CRAWLER_SEARCH_DEBUG_FLAG') == 'true'):
        debug_mode   = 1;

    sigevent_type     = 'INFO'
    sigevent_category = 'UNCATEGORIZED'
    sigevent_description = 'SIGEVENT_DESCRIPTION';
    sigevent_data        = 'SIGEVENT_DATA';
    sigevent_debug_flag  = 1;

    # Raise a sigevent that should work.
    os.environ["MYENV"] = "SOME_THING_MAGIC";
    print("os.getenv('MYENV','')",os.getenv("MYENV",""));

    raise_sigevent_wrapper(sigevent_type,
                           sigevent_category,
                           sigevent_description,
                           sigevent_data,
                           sigevent_debug_flag);

    # Raise another sigevent but with a longer description.

    sigevent_description = 'FOLLOWED_IS_A_REALLY_LONG_MESSAGE_WHICH_WILL_BE_TRUNCATED:We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America.'

    sigevent_debug_flag  = 0;
    raise_sigevent_wrapper(sigevent_type,
                           sigevent_category,
                           sigevent_description,
                           sigevent_data,
                           sigevent_debug_flag);
