#  Copyright 2017, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

import os
import time
from time import strftime

from get_local_time                import get_local_pdt_time;

#------------------------------------------------------------------------------------------------------------------------
# Function to log a message to screen.
def log_this(i_log_type,      # Possible types are {INFO,WARN,ERROR}
             i_function_name, # Where the logging is coming from.  Useful in debuging if something goes wrong.
             i_log_message):  # The text you wish to log screen.

    # Thu Oct 13 00:35:30 2016 INFO [modis_level2_combiner] MESSAGE

    localtime = get_local_pdt_time();
    now_is = strftime("%a %b %d %H:%M:%S %Y",localtime);

    print(now_is + " " + i_log_type + " [" + i_function_name + "] " + i_log_message);

if __name__ == "__main__":

    g_routine_name = "log_this";
    log_this("INFO",g_routine_name,g_routine_name + " " + "UNIT_TEST");
